apiVersion: v1
kind: Namespace
metadata:
  name: git
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea
data:
  ALLOW_ONLY_INTERNAL_REGISTRATION: "${ALLOW_ONLY_INTERNAL_REGISTRATION}"
  DISABLE_REGISTRATION: "${DISABLE_REGISTRATION}"
  ENABLE_AUTO_REGISTRATION: "${ENABLE_AUTO_REGISTRATION}"
  USER_GID: "1000"
  USER_UID: "1000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: git
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitea
      version: v1
  template:
    metadata:
      labels:
        app: gitea
        version: v1
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: gitea
            optional: false
        image: gitea/gitea:1.18
        imagePullPolicy: Always
        name: gitea
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: gitea
        - mountPath: /etc/timezone
          name: timezone
        - mountPath: /etc/localtime
          name: localtime
      volumes:
      - hostPath:
          path: /storage/gitea
          type: DirectoryOrCreate
        name: gitea
      - hostPath:
          path: /etc/timezone
          type: FileOrCreate
        name: timezone
      - hostPath:
          path: /etc/localtime
          type: FileOrCreate
        name: localtime
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: git
spec:
  internalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: gitea
    version: v1
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt
  namespace: registry
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: ${LETSENCRYPT_EMAIL}
    privateKeySecretRef:
      name: account-key
    solvers:
    - http01:
       ingress:
         class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: git-certificate
  namespace: git
spec:
  secretName: git-certificate
  issuerRef:
    name: letsencrypt
  dnsNames:
  - ${GITEA_SERVER_URL}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: git
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/proxy-body-size: "300m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
spec:
  tls:
  - hosts:
      - ${GITEA_SERVER_URL}
    secretName: git-certificate
  rules:
  - host: ${GITEA_SERVER_URL}
    http:
      paths:
      - backend:
          service:
            name: gitea
            port:
              number: 3000
        path: /
        pathType: ImplementationSpecific
